### ISSUE TITLE
How to debug built in memory scripts

### ISSUE THREAD

**Issue by patrickds** [Microsoft/vscode-node-debug2#139]
Hi :)
I'm trying to debug coffescript from vscode and I'm possibly having the a problem related to the following statement I found on the readme:

`Ensure that outFiles is set correctly in your launch config, so that VS Code can find your scripts and its sourcemaps before they're loaded in Node. Example: "outFiles": ["${workspaceRoot}/out/**/*.js"]. (This may not be possible if your scripts are built in-memory or on demand.)`

The coffee files are compiled on the fly by the coffee-register with inline source maps.
I got to the point where all the source maps are working correctly but vscode seems not to find the generated files since they only exist in memory 😅 
If I use a `debugger` clause vs code stops on the right line in the right source file! But breakpoint are still grey..So I'm wondering if it is possible to set breakpoint from vscode in this case..

Can someone help?

Thanks in advance 🙂

**Comment by roblourens** [comment]
If the sourcemaps are generated with the correct details, then it should be able to resolve them even without `outFiles`. But, you may not hit breakpoints in code that runs immediate when the script is loaded, because of the time it takes to resolve the breakpoints.

If the breakpoints are still gray after the script is loaded then there is probably a sourcemap issue. Try running the `.scripts` command in the console to see how scripts are being resolved: https://github.com/Microsoft/vscode-node-debug2#the-scripts-command

**Comment by patrickds** [comment]
So, the issue was solved setting `"protocol": "inspector"` as it is not the default for node < 8.0 even though it is supported since node 6.3+ as seen [here](https://github.com/Microsoft/vscode/issues/24764).
And it seems that the source maps for node < 6.3 are not working as seen [here](https://github.com/Microsoft/vscode-node-debug/issues/61)

I will close the issue now, thanks for the support 🙂

**Comment by roblourens** [comment]
Glad to hear it. I should have mentioned that as well.
