### ISSUE TITLE
[process.pid, process.version, process.arch] interruption on debugging mocha tests

### ISSUE THREAD

**Issue by Spown** [microsoft/vscode-node-debug2#144]
I just moved to Node 8.5.0 and when debugging a mocha test script with internals skipped a VM tab opens with the content 

```js
[process.pid, process.version, process.arch]
```
It has no context, only ``global`` is visible. none of these process things are inspectable. No error. Nothing. Resuming execution works ok.

This should be ignored since I skip internals via 

```js
			,"skipFiles": [
				"<node_internals>/**",
				"**/node_modules/**"
			]
```

![](https://drive.google.com/uc?id=0B-OJBofmehO3R0lScWduNGpkMWs)

If I comment either or both of ``skipFiles`` patterns out - it works fine. 

The project itself is private, so I won't be sharing it (at least not in it's entirety) but I don't think it matters - nothing in the stack belongs to it. Everything non-internal belongs to mocha.

![](https://drive.google.com/uc?id=0B-OJBofmehO3dzU0Qk12dE90Z0E)

**Comment by roblourens** [comment]
That's a weird one. That script shouldn't be skipped by your skipFiles, as it's not a script from node. But, the tooltip does say that it should be skipped. I don't know why it's pausing in that script. 

> If I comment either or both of skipFiles patterns out - it works fine.

Can you clarify "it works fine"? Does it not pause there when you comment out the patterns?

This isn't the first weird issue that's been reported in Node 8.5 specifically. That script can't even be part of that stack, it's evaluated by the debug adapter.

**Comment by roblourens** [comment]
Also can you run with `"trace": true` and upload the full log here?

**Comment by Spown** [comment]
>>  If I comment either or both of skipFiles patterns out - it works fine.

> Can you clarify "it works fine"? Does it not pause there when you comment out the patterns?

Yes, it just works as expected, without interruption, like it did with Node 7 and 6

>This isn't the first weird issue that's been reported in Node 8.5 specifically. That script can't even be part of that stack, it's evaluated by the debug adapter.

Don't know if this matters, but VSC's About shows 

Version 1.16.1
Commit 27492b6bf3acb0775d82d2f87b25a93490673c6d
Date 2017-09-14T16:38:23.027Z
Shell 1.7.3
Renderer 58.0.3029.110
__Node 7.9.0__
Architecture x64

While ``node -v`` yelds ``v8.5.0``. Yes, I did restart Windows after Node update.

>Also can you run with "trace": true and upload the full log here?

With ``trace": true`` It starts to interrupt right on the first line of the mocha test script. I tested 10 times just now and 8/10 times it stopped in the very start. The rest 2 times it were on this VM bit from the original post. Does it supposed to produce any extra output into Debug Console? Because it didn't.

**Comment by roblourens** [comment]
With the trace option, you should get a message like `Verbose logs are written to:
/var/folders/tx/p0ycbfpj37786p760wwdg6y80000gn/T/vscode-node-debug2.txt`at the top of the Debug Console. I assume you don't have stopOnEntry set?

**Comment by Spown** [comment]
Yeah, it was turned off. I expunged env and path parts from the [log](https://drive.google.com/uc?id=0B-OJBofmehO3aTRkbzZONmtNVUU)

**Comment by roblourens** [comment]
It looks like the app is taking a long time to start up, and this is node breaking on start (I always tell it to break on start, so I can set breakpoints before continuing). But if it takes too long, I assume the break on start event didn't come and I stop waiting for it. Is this a slow machine? Or it may be that node 8.5 is slower here. I will increase the timeout.

**Comment by roblourens** [comment]
Try it out in the next insiders and let me know if it's improved. If not, there might be one more thing I can do.

**Comment by Spown** [comment]
>Is this a slow machine?

Its 2,8Ghz so I wouldn't call it slow. However it has 6 cores and I assume both debugger and the main process would imploy only one so its... Never mind, I just turned 3 cores off (this normally allows older programs run 2x faster) and absolutely nothing changed. My whole sys never picked once. Every spike is a single run here.
 ![](https://drive.google.com/uc?id=0B-OJBofmehO3ZlMwQnB0anhxUVk)

Mocha sticking it's staff in every crevice of my rather comprehensible project observed by the debugger and run under, apparently, slower Node 8 doesn't make it very fast but I don't think it's the problem. As I said - removing ``"<node_internals>/**"`` from ``skipFiles`` always does the trick. It may be caused by the exceeded timeout in the end, by the deley is probably caused by something that is linked to file system. So instead of an increased provisional timeout I would look for the bottleneck...

Anyway I don't think this resolves the issue. Why did you close it?

**Comment by roblourens** [comment]
I'll leave it open for me to investigate some more on other windows machines. But I'm testing on a slow Windows VM and it's still a very fast process, and I have no idea what would cause it to take so long. Surely the timeout will fix it but Insiders is not updating right now.

**Comment by Spown** [comment]
Thank you.

I've spend the day working like that and I can't really feel any difference in speed with skipping node_internals or without. Well, that is if not taking my working speed impediment into account...

**Comment by roblourens** [comment]
Would also appreciate if you try it with an earlier version of Node 8 besides 8.5, to see if it's any different.

**Comment by Spown** [comment]
8.2.1 - breaks on the first line of the script 8 times out of 10, the rest 2 - the VM thing. pretty much the same as 8.5.
8.0.0 - breaks on the first line of the script 9 times out of 10, 1th/10 - it opens a VM tab, and crashes: the tab is empty and underneath a blue progress bar runner is in progress forever. I can't resume and on stop I get 
![](https://drive.google.com/uc?id=0B-OJBofmehO3Z3ZOQkpyTkhGbHc) 
7.9.0 - Everything is fine. Stepping over into another file takes slightly more time than with 8.* or at least it feels like it. I think I'll stick with this ver for the time being.

**Comment by Deilan** [comment]
As of Node.js 8.7.0, VS Code 1.17.1 the issue is being reproduced on 2 windows machines and 1 macOS machine. It is not being reproduced on Node.js 7.10.1.

**Comment by roblourens** [comment]
I bumped the timeout for the initial debug break again, and adding a little more logging there. Please try the next Insiders build (on Monday) and if it still happens, upload the log from `"trace": true`.

**Comment by roblourens** [comment]
Have either of you tried Insiders this week? Did it help?

**Comment by Spown** [comment]
I'm on Node 7 right now and I'm not working on tests. I'll check as soon as I'm able.

**Comment by Deilan** [comment]
Tried it on the latest Insiders as of 02.11.2017, Node.js 8.8.1. The issue is still being reproduced the same way.

[vscode-node-debug2.txt](https://github.com/Microsoft/vscode-node-debug2/files/1439122/vscode-node-debug2.txt)

**Comment by Deilan** [comment]
Tried on the latest Insiders build as of 02.11.2017, Node.js 8.8.1 x64. The problem is still there. Here's the logs: [vscode-node-debug2.txt](https://github.com/Microsoft/vscode-node-debug2/files/1439141/vscode-node-debug2.txt)

**Comment by Deilan** [comment]
@roblourens Here's a repo, which could be used to stably reproduce the issue:
https://github.com/deilan/node-typescript-vscode

Just clone, install deps and launch debugging.

**Comment by roblourens** [comment]
Thanks for the repo. The logs are very interesting. When I run this with Node 7.10, it takes less than 200ms to start. When I run with Node 8.8.1, it takes 2-3 seconds. The current limit is 5s, which you must be getting. When I run with Node 9 it took... at least a minute. I'm curious whether you get the same results with Node 9.

It seems like the "real" problem is that this setup is triggering some crazy case in Node 8+, which might be worth filing an issue for on Node itself. But clearly the adapter should handle launch times far longer than what I thought was reasonable, so I will just increase the timeout again or remove it entirely.

**Comment by Spown** [comment]
So, now I'm experience this on Node 9.4. I'm not always getting to see this ``[process.pid, process.version, process.arch]`` but  it always stops on the first line of the main debugged test script. Also it doesn't say the break is originated from some VM as it did before, but it accuses my script of containing an anonymous function at the address 1:1 where nothing of sorts exists.
![](https://drive.google.com/uc?id=1NRVSEjBd6-Sa7QBwYAxOX3HxnUpl4PNr)

**Comment by Spown** [comment]
[log](https://drive.google.com/uc?id=1iF9u8CdABmdxWTXGQRYMTeJIfSCEzwLv)

**Comment by roblourens** [comment]
Thanks for the log. It shows the same thing that I described before - the script takes a very long time to start. So I think there's still a bug upstream. I don't think I ever saw your code, were you using node-ts as well? From the part of the stack that I can see, I'm guessing you're using something that transpiles scripts dynamically.

I will push a change to respect the "timeout" launch config parameter while waiting for the script to pause on entry, so you can set `"timeout": 20000` or whatever it takes. That won't make it any faster but you should stop getting stuck at script entry. That line is a valid place to stop because it's just inside Node's module wrapper.

**Comment by Spown** [comment]
>From the part of the stack that I can see, I'm guessing you're using something that transpiles scripts dynamically.

No, not really. I'm using pure js. However I can't vouch for every module in my node_modules tree. Much less with Mocha on top.

Thanks for the option.

**Comment by Deilan** [comment]
@roblourens  I've rerun debug with `trace: true` for a sample project using `nodemon` and `ts-node` for different versions of VS Code (1.20.0 Stable and 1.21.0 Insiders) and Node.js (8.9.4 and 9.5.0). The issue is being reproduced on Node.js 9.5.0 and both versions of VS Code, and not being reproduced on Node.js 8.9.4 and both versions of VS Code. Further in the comment there are details about these launches.

Sample project: https://github.com/deilan/node-typescript-vscode

**VS Code version**: Code - Insiders 1.21.0-insider (ef42990520a856451ba5ad6fa1d299b0e0c185a2, 2018-02-12T05:14:21.574Z)
**OS version**: Windows_NT x64 10.0.15063
**Node.js version**: 8.9.4 x64
**Result**: Is not reproduced.
**Log**: [debugadapter.txt](https://github.com/Microsoft/vscode-node-debug2/files/1715884/debugadapter.txt)


**VS Code version**: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
**OS version**: Windows_NT x64 10.0.15063
**Node.js version**: 8.9.4 x64
**Result**: Is not reproduced.
**Log**: [debugadapter.txt](https://github.com/Microsoft/vscode-node-debug2/files/1715890/debugadapter.txt)


**VS Code version**: Code - Insiders 1.21.0-insider (ef42990520a856451ba5ad6fa1d299b0e0c185a2, 2018-02-12T05:14:21.574Z)
**OS version**: Windows_NT x64 10.0.15063
**Node.js version**: 9.5.0 x64
**Result**: Debugger breaks on the first line of `index.ts`
**Log**: [debugadapter.txt](https://github.com/Microsoft/vscode-node-debug2/files/1715902/debugadapter.txt)


**VS Code version**: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
**OS version**: Windows_NT x64 10.0.15063
**Node.js version**: 9.5.0 x64
**Result**: Debugger breaks on the first line of `index.ts`
**Log**: [debugadapter.txt](https://github.com/Microsoft/vscode-node-debug2/files/1715900/debugadapter.txt)

**Comment by roblourens** [comment]
Thanks, this just shows the same problem as before. You can try setting "timeout" to a larger value (in insiders) and that should work around the issue.

**Comment by Deilan** [comment]
@roblourens Is there an upstream bug posted for it?

**Comment by roblourens** [comment]
Not that I know of. I haven't tried to reduce it from your project, and I haven't seen @Spown's code so I don't know what's common between the two projects.

**Comment by Deilan** [comment]
@roblourens Is there something I can help with reducing from my project? So far I've made [my sample project](https://github.com/deilan/node-typescript-vscode) as simple as possible.

**Comment by Spown** [comment]
My project is an inhause made CMS. It is private for several different reasons at least for now. The mocha tests are not, but what good they are without the tested code? Sorry.

**Comment by Deilan** [comment]
@Spown The issue is being reproduced only within this project and nowhere else in your experience? How do you think, is there any possibility to create a sample project, which could be used to reproduce the issue?

**Comment by Spown** [comment]
Well, this is the only project where I debug mocha tests. In other, less comprehensive projects I write the tests without debugging - I only debug the projects themselves.

**Comment by roblourens** [comment]
Trying this again, maybe it's actually simpler than I thought. When it reproes with the skipFiles set, it has to wait for user code to load. In @Deilan's case that's slow because of ts-node, I don't know about @Spown but maybe mocha takes a while before it gets to test code.

When it doesn't repro without skipFiles set, it doesn't have to wait for user code to load.

I still can't decide what the right fix is. Getting rid of the timeout would fix it but I'm worried that's not safe. I could also wait to apply the skipFiles patterns until that initial break but that would need work to pause at the right place when stopOnEntry is set.

I go on vacation soon and don't want to make either of these changes right before I leave. Hopefully the "timeout" workaround is enough for now.

**Comment by Spown** [comment]
I've totally forgot I had another project that I debug on test. That one is public: [i18n-node](Spown/i18n-node). I've just came back to update it's dependencies and got this error on debugging tests...

the launch is 
```json
{
	"name": "test"
	,"type": "node"
	,"request": "launch"
	,"cwd": "${workspaceRoot}"
	,"env": {
		"NODE_ENV": "test.development",
		"DEBUG": "*,-mocha:*"
	}
	,"program": "${workspaceRoot}\\node_modules\\mocha\\bin\\_mocha"
	,"runtimeExecutable": null
	,"stopOnEntry": false
	,"args": ["--no-timeouts"] //"test/i18n.mf", , "--timeout", "10s", "--async-only"
	,"console": "integratedTerminal"
	,"skipFiles": [
		"**/node_modules/**",
		"<node_internals>/**"
	]
}
```

**Comment by preco21** [comment]
I got some sort of similar issue while working on somewhat slow machine. The issue was preventing `stopOnEntry: false` with `ts-node/register` to work when the time taken launching debugger takes longer than 10 seconds as @roblourens described (nearly always happens when you start debugger right after launching VSCode, which is busy that time).

For those who looking for a workaround for `ts-node/register` before the issue resolved, use this config:

> `timeout` is the point (default 10000).
```json
{
  "name": "[TS] Launch debugger",
  "type": "node",
  "request": "launch",
  "cwd": "${workspaceFolder}",
  "runtimeArgs": ["--nolazy", "--require", "ts-node/register"],
  "args": ["${relativeFile}"],
  "autoAttachChildProcesses": true,
  "protocol": "inspector",
  "console": "integratedTerminal",
  "stopOnEntry": false,
  "sourceMaps": true,
  "smartStep": true,
  "disableOptimisticBPs": true,
  "skipFiles": ["<node_internals>/**/*.js", "**/ts-node/**/*.ts"],
  "env": {"TS_NODE_FILES": "true", "NODE_ENV": "development"},
  "timeout": 30000
}
```

But still, I'm not sure if this is the real workaround to go, I haven't tested it as much.

**Comment by ddehghan** [comment]
I only had to add "timeout": 30000, to make it work. 

> {
>             "type": "node",
>             "request": "launch",
>             "name": "Debug Dev Local - API",
>             "args": ["src/main.ts"], 
>             "cwd": "${workspaceFolder}/dm-api",
>             "runtimeArgs": ["--nolazy", "-r", "ts-node/register", "-r", "tsconfig-paths/register"],
>             "timeout": 30000,
>             "sourceMaps": true,
>             "protocol": "inspector",
>             "env": {
>                 "DEV_ENV": "dev",
>             },
>             "stopOnEntry": false,
>             "console": "integratedTerminal",
>             "smartStep: true
> }

just removing the timeout will make it so it automatically stops on start regardless of stopOnEntry value.

**Comment by connor4312** [comment]
We have a [new debugger](https://github.com/microsoft/vscode-js-debug/) which uses a different and (in theory) more reliable version of break on start, so this should no longer be an issue. Please open a new issue on that repo if it is.
