### ISSUE TITLE
Pass configuration arguments to NodeDebugAdapter

### ISSUE THREAD

**Issue by orehmane** [Microsoft/vscode-node-debug2#203]
Hello!

Is it possible to pass arguments to `NodeDebugAdapter` when it's constructed? Specifically, I'd like to pass `enableSourceMapCaching` in order to disable source map caching.

The root cause of this request is that our cached source maps are being used even after a rebuild (we are using Webpack watching to rebuild the project on source changes). This is the launch configuration in question :
```
{
      "type": "node",
      "request": "launch",
      "name": "INTERNAL PROJECT NAME",
      "program": "${workspaceFolder}/node_modules/INTERNAL_PROGRAM/bin/INTERNAL_PROGRAM",
      "args": [
        "start",
        "--path",
        "${workspaceFolder}",
      ],
      "protocol": "inspector"
    },
```

Based upon trace output (and the behavior - after rebuilds, breakpoints still work, but are off by a few lines), it seems that VS Code, upon a request to the project, finds the cached source map and never invalidates it.

This is the trace logging that made me think it was an overzealous cache - this occurs even after restarting VS Code and running debugging again:
```
Sourcemaps.downloadSourceMapContents: Reading cached sourcemap file from /var/folders/yy/5fggx3nd1b12fkhnb3hv9q580000gq/T/com.microsoft.VSCode/node-debug2/sm-cache/be345fed71
SourceMaps.loadSourceMapContents: Reading local sourcemap file from /var/folders/yy/5fggx3nd1b12fkhnb3hv9q580000gq/T/com.microsoft.VSCode/node-debug2/sm-cache/be345fed712c1a6
```

Please let me know if passing that argument is possible, or if there's a better way to achieve my goal.

Thank you very much!

**Comment by roblourens** [comment]
Yeah, I will add an option for this.

They should only be cached when your sourcemaps have to be downloaded from a URL. You should be able to work around it by changing your setup to point at a local file instead of the URL. Or possibly by using outFiles to preload your sourcemaps from disk.

If you're using webpack-dev-server or something then they may not exist on disk.

**Comment by roblourens** [comment]
@weinand If I remember correctly, the sourcemap caching was mainly driven by EH debugging to cache the downloaded sourcemaps from vscode. What do you think about enabling for extensionHost but not node2 by default?

**Comment by orehmane** [comment]
@roblourens If I read that correctly, caching is disabled by default now? Which release will this be in?

**Comment by roblourens** [comment]
I just added the setting to optionally disable it for now. Maybe I'll change it to disable by default, not sure yet. It will be in Insiders next week or 1.28 in a couple weeks.

**Comment by orehmane** [comment]
Okay, great! And we just set `enableSourceMapCaching: false` in `launch.json`?

**Comment by roblourens** [comment]
Correct

**Comment by weinand** [comment]
yes, for EH debugging the sourcemaps and TS sources are some MB and downloading them on every step slows down stepping considerably (especially if you have no internet connection ;-)
Since the commit ID is part of the URL the cache never becomes stale.

When I was looking into Webpack I noticed that they generate (or are able to generate) unique filenames for the packed JS too. With that it should not result it stale cache entries.
So you might want to use a file name schema that changes for every webpack...

@roblourens I'm fine with caching only for EH debugging.

**Comment by roblourens** [comment]
Ok, yeah I'll leave the option but disable it by default for node2.
