### ISSUE TITLE
package vscode-node-debug2

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-node-debug2#258]
In the VSCode build, `vscode-node-debug2` is the extension with the most files (354).

Any chance the extension can be webpacked?

**Comment by roblourens** [comment]
We tried, but using the nls library from a node module (vscode-chrome-debug-core) was an issue that we weren't able to solve.

I'll do you one better. Since vscode-js-debug is the future, we will soon be able to stop shipping vscode-node-debug2 by default. But I think there is more transitional work to do before we are ready for that.
