### ISSUE TITLE
console.log doesn't appear

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-node-debug2#81]
[vscode-node-debug2.txt](https://github.com/Microsoft/vscode-node-debug2/files/727811/vscode-node-debug2.txt)

**Comment by nbransby** [comment]
Im having the same issue, can't see any output

**Comment by roblourens** [comment]
A few people have seen this issue: https://github.com/Microsoft/vscode/issues/19750 - which looks similar but is calls to `process.stdout.write()` not showing up in the debug console. Apparently there are some logging libraries that use `process.stdout.write` instead of `console.log`. See some details in that thread. Is it possible that you're using `process.stdout.write`?

This issue was from a call to `console.log` not showing up, and I still don't know why that was happening.
