### ISSUE TITLE
`npm install --only=production` fails

### ISSUE THREAD

**Issue by dlebu** [Microsoft/vscode-node-debug2#96]
This is because `vscode` is a dev dependency and used in the postinstall script.

**Comment by roblourens** [comment]
Actually, it should be a dev dependency, because we don't want to ship it, and you definitely don't either. I'm not a huge fan of the pattern we use with the postinstall script, but I can't do anything about it right now. Can you just remove that script entry before running npm install? Or, maybe there is a flag to run it without running the script. Also, I think `npm install --force` will cause it to ignore errors, so you could try that.

**Comment by dlebu** [comment]
Makes sense, we should not ship this package. I'll try the force option instead, thanks!
